# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/inference.proto\x12\x10\x61thena.inference\"\x07\n\x05\x45mpty\"/\n\x08ModelRef\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"(\n\tLoadReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"a\n\x10InferenceRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\x02\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\t\"Y\n\x0eInferenceReply\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07outputs\x18\x02 \x03(\x02\x12\x12\n\nlatency_ms\x18\x03 \x01(\x01\x12\x0e\n\x06status\x18\x04 \x01(\t\"G\n\x10ModelStatusReply\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\xc8\x02\n\x10InferenceService\x12\x44\n\tLoadModel\x12\x1a.athena.inference.ModelRef\x1a\x1b.athena.inference.LoadReply\x12\x46\n\x0bUnloadModel\x12\x1a.athena.inference.ModelRef\x1a\x1b.athena.inference.LoadReply\x12P\n\x0eGetModelStatus\x12\x1a.athena.inference.ModelRef\x1a\".athena.inference.ModelStatusReply\x12T\n\x0cRunInference\x12\".athena.inference.InferenceRequest\x1a .athena.inference.InferenceReplyB\x12Z\x10\x61thena/inferenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020athena/inference'
  _globals['_EMPTY']._serialized_start=43
  _globals['_EMPTY']._serialized_end=50
  _globals['_MODELREF']._serialized_start=52
  _globals['_MODELREF']._serialized_end=99
  _globals['_LOADREPLY']._serialized_start=101
  _globals['_LOADREPLY']._serialized_end=141
  _globals['_INFERENCEREQUEST']._serialized_start=143
  _globals['_INFERENCEREQUEST']._serialized_end=240
  _globals['_INFERENCEREPLY']._serialized_start=242
  _globals['_INFERENCEREPLY']._serialized_end=331
  _globals['_MODELSTATUSREPLY']._serialized_start=333
  _globals['_MODELSTATUSREPLY']._serialized_end=404
  _globals['_INFERENCESERVICE']._serialized_start=407
  _globals['_INFERENCESERVICE']._serialized_end=735
# @@protoc_insertion_point(module_scope)
