# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import inference_pb2 as proto_dot_inference__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/athena.inference.InferenceService/LoadModel',
                request_serializer=proto_dot_inference__pb2.ModelRef.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.LoadReply.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/athena.inference.InferenceService/UnloadModel',
                request_serializer=proto_dot_inference__pb2.ModelRef.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.LoadReply.FromString,
                _registered_method=True)
        self.GetModelStatus = channel.unary_unary(
                '/athena.inference.InferenceService/GetModelStatus',
                request_serializer=proto_dot_inference__pb2.ModelRef.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.ModelStatusReply.FromString,
                _registered_method=True)
        self.RunInference = channel.unary_unary(
                '/athena.inference.InferenceService/RunInference',
                request_serializer=proto_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.InferenceReply.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=proto_dot_inference__pb2.ModelRef.FromString,
                    response_serializer=proto_dot_inference__pb2.LoadReply.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=proto_dot_inference__pb2.ModelRef.FromString,
                    response_serializer=proto_dot_inference__pb2.LoadReply.SerializeToString,
            ),
            'GetModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStatus,
                    request_deserializer=proto_dot_inference__pb2.ModelRef.FromString,
                    response_serializer=proto_dot_inference__pb2.ModelStatusReply.SerializeToString,
            ),
            'RunInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RunInference,
                    request_deserializer=proto_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=proto_dot_inference__pb2.InferenceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'athena.inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('athena.inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/athena.inference.InferenceService/LoadModel',
            proto_dot_inference__pb2.ModelRef.SerializeToString,
            proto_dot_inference__pb2.LoadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/athena.inference.InferenceService/UnloadModel',
            proto_dot_inference__pb2.ModelRef.SerializeToString,
            proto_dot_inference__pb2.LoadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/athena.inference.InferenceService/GetModelStatus',
            proto_dot_inference__pb2.ModelRef.SerializeToString,
            proto_dot_inference__pb2.ModelStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/athena.inference.InferenceService/RunInference',
            proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            proto_dot_inference__pb2.InferenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
