apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena-control-plane
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: athena-control-plane
  template:
    metadata:
      labels:
        app: athena-control-plane
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: control-plane
          image: "{{ .Values.controlPlane.image }}"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
