# .github/workflows/ci.yaml
name: Athena CI/CD Pipeline

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write

jobs:
  # -----------------------------
  # Job 1: Diagnose & Validate Structure (Run First)
  # -----------------------------
  diagnose-structure:
    name: Diagnose Repository Structure
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print Working Directory and List Contents
        run: |
          echo "Current working directory: $(pwd)"
          echo "Root directory contents:"
          ls -la
          echo "Contents of 'athena' directory:"
          if [ -d "athena" ]; then
            ls -la athena/
          else
            echo "ERROR: 'athena' directory not found in root."
            exit 1
          fi
          echo "Contents of 'athena-ui' directory:"
          if [ -d "athena-ui" ]; then
            ls -la athena-ui/
          else
            echo "ERROR: 'athena-ui' directory not found in root."
            exit 1
          fi
          echo "Searching for key files:"
          find . -name "CMakeLists.txt" -type f
          find . -name "package-lock.json" -type f
          find . -name "requirements.txt" -type f

  # -----------------------------
  # Job 2: Build C++ Core (CMake)
  # -----------------------------
  build-core:
    name: Build C++ Core
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: diagnose-structure # Ensure structure is validated first
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config protobuf-compiler libprotobuf-dev libprotoc-dev libgrpc++-dev git

      - name: Configure & Build C++ Core
        working-directory: athena/core
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -- -j$(nproc)

      - name: Run C++ Tests
        working-directory: athena/core/build
        run: |
          if [ -f CTestTestfile.cmake ] || [ -d tests ]; then
            ctest --output-on-failure || true
          fi

  # -----------------------------
  # Job 3: Python Control Plane Tests
  # -----------------------------
  python-tests:
    name: Python Tests (Control Plane)
    runs-on: ubuntu-latest
    needs: build-core
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r athena/control_plane/requirements.txt
          python -m pip install pytest grpcio grpcio-tools protobuf

      - name: Generate gRPC Stubs from Proto
        run: |
          mkdir -p athena/control_plane/proto
          python -m grpc_tools.protoc -Iathena/core/proto --python_out=athena/control_plane/proto --grpc_python_out=athena/control_plane/proto athena/core/proto/inference.proto

      - name: Run Pytest (Control Plane)
        working-directory: athena/control_plane
        run: |
          pytest -q

  # -----------------------------
  # Job 4: Frontend Build (Next.js)
  # -----------------------------
  frontend-build:
    name: Frontend Build (Next.js)
    runs-on: ubuntu-latest
    needs: python-tests
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: athena-ui/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: athena-ui
        run: npm ci

      - name: Lint (Optional)
        working-directory: athena-ui
        run: |
          if npm run -s lint; then echo "Lint passed"; else echo "Lint failed, but continuing"; fi

      - name: Build Next.js Application
        working-directory: athena-ui
        run: npm run build

  # -----------------------------
  # Job 5: Build & Push Docker Images (Only on main branch)
  # -----------------------------
  build-and-push:
    name: Build & Push Docker Images (GHCR)
    runs-on: ubuntu-latest
    needs: [build-core, python-tests, frontend-build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || github.token }}

      - name: Build and Push Control Plane Image
        run: |
          docker build -f athena/docker/control-plane.Dockerfile -t ghcr.io/${{ github.repository_owner }}/athena-control-plane:latest .
          docker push ghcr.io/${{ github.repository_owner }}/athena-control-plane:latest

      - name: Build and Push Core Image
        run: |
          docker build -f athena/docker/athena-core.Dockerfile -t ghcr.io/${{ github.repository_owner }}/athena-core:latest .
          docker push ghcr.io/${{ github.repository_owner }}/athena-core:latest