name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential
      - name: Build core
        run: |
          cd core
          mkdir -p build && cd build
          cmake ..
          cmake --build . -- -j$(nproc)
      - name: Run C++ tests (if any)
        run: |
          if [ -d core/build ]; then
            cd core/build && ctest --output-on-failure || true
          fi

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install control-plane dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r control-plane/requirements.txt
          pip install pytest
      - name: Run pytest (control-plane)
        run: |
          if [ -d control-plane ]; then
            cd control-plane
            pytest -q || true
          fi

  build-and-push:
    needs: [build-core, python-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push control-plane image
        run: |
          docker build -f docker/control-plane.Dockerfile -t ghcr.io/${{ github.repository_owner }}/athena-control-plane:latest .
          docker push ghcr.io/${{ github.repository_owner }}/athena-control-plane:latest
      - name: Build and push core image
        run: |
          docker build -f docker/athena-core.Dockerfile -t ghcr.io/${{ github.repository_owner }}/athena-core:latest .
          docker push ghcr.io/${{ github.repository_owner }}/athena-core:latest
