# .github/workflows/ci.yaml
name: Athena CI

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write

jobs:
  # -----------------------------
  # Build the C++ core (CMake)
  # -----------------------------
  build-core:
    name: Build C++ core
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config protobuf-compiler libprotobuf-dev libprotoc-dev libgrpc++-dev git

      - name: Configure & build
        # Adjusted path: core directory is in the root, not athena/core
        working-directory: core 
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -- -j$(nproc)

      - name: Run C++ tests
        # Adjusted path
        working-directory: core/build
        run: |
          if [ -f CTestTestfile.cmake ] || [ -d tests ]; then
            ctest --output-on-failure || true
          fi

  # -----------------------------
  # Python control-plane tests
  # -----------------------------
  python-tests:
    name: Python tests (control-plane)
    runs-on: ubuntu-latest
    needs: build-core
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          # Adjusted path: control_plane directory is in the root
          python -m pip install -r control_plane/requirements.txt
          python -m pip install pytest grpcio grpcio-tools protobuf

      - name: Generate python gRPC stubs
        run: |
          # Adjusted path: proto directory in control_plane, and proto files location
          mkdir -p control_plane/proto
          python -m grpc_tools.protoc -Icore/proto --python_out=control_plane/proto --grpc_python_out=control_plane/proto core/proto/inference.proto

      - name: Run pytest (control-plane)
        # Adjusted path
        working-directory: control_plane
        run: |
          pytest -q

  # -----------------------------
  # Frontend build (Next.js)
  # -----------------------------
  frontend-build:
    name: Frontend Build (Next.js)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          # Adjusted path: package-lock.json is in the root
          cache-dependency-path: package-lock.json 

      - name: Install dependencies (frontend)
        # No need for working-directory if athena-ui was the root
        # If athena-ui is a subdirectory, add: working-directory: athena-ui
        # Based on your 'ls' output, it looks like the frontend *is* the root,
        # and the directory name shown as 'control_plane' in your ls output might be misleading
        # Let's assume the frontend files (package.json, etc.) are in the repo root
        run: npm ci 

      - name: Lint (optional)
        # Same assumption as above
        run: |
          if npm run -s lint; then echo "lint ok"; else echo "lint failed but continuing"; fi

      - name: Build Next.js
        # Same assumption as above
        run: npm run build

  # -----------------------------
  # Build & push Docker images (only on main)
  # -----------------------------
  build-and-push:
    name: Build & Push Docker Images (GHCR)
    runs-on: ubuntu-latest
    needs: [build-core, python-tests, frontend-build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || github.token }}
      - name: Build and push control-plane image
        run: |
          # Adjusted Dockerfile path if it's in the root or core directory
          # Assuming control-plane Dockerfile might be in /control_plane or /docker
          # You'll need to adjust this path based on where control-plane.Dockerfile actually is
          # For now, assuming it's in /docker directory
          docker build -f docker/control-plane.Dockerfile -t ghcr.io/${{ github.repository_owner }}/athena-control-plane:latest .
          docker push ghcr.io/${{ github.repository_owner }}/athena-control-plane:latest
      - name: Build and push core image
        run: |
          # Adjusted Dockerfile path - assuming it's in /docker directory
          # You'll need to adjust this path based on where athena-core.Dockerfile actually is
          docker build -f docker/athena-core.Dockerfile -t ghcr.io/${{ github.repository_owner }}/athena-core:latest .
          docker push ghcr.io/${{ github.repository_owner }}/athena-core:latest